server:
  port: 9090


spring:
  application:
    name: spring-admin
  thymeleaf:
    check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true